Algoritmo "Vamos calcular o seu IMC"
// 
//
//
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/3/2022
Var
// declaração de variaveis 
alt, peso, x : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

//leitura de dados ...
escreval ("Digite a sua altura: ")
leia (alt)
escreval ("Digite o seu peso: ")
leia (peso)

x <- ( alt / peso)

escreval ("Seu IMC e: ", (x))

Fimalgoritmo