Algoritmo "Vamos calcular o seu IMC"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/3/2022
Var
// Seção de Declarações das variáveis 
alt, peso, x : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite a sua altura: ")
leia (alt)
escreval ("Digite o seu peso: ")
leia (peso)

x <- ( alt / peso)

escreval ("Seu IMC é: ", (x))

Fimalgoritmo