Algoritmo "Cálculo de Altura Pessoas "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/03/2022
Var
// Seção de Declarações das variáveis 

h1, h2, h3, h4, h5, m : real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreva



Fimalgoritmo