Algoritmo "Exemplo01"
//  
//  
// 
//

// Autor(a)    : Marinho Silva
// Data atual  : 26/3/2022

Var
// declaração de variaveis 
x, y, z : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x <- 0
y <- 0
z <- 0

//leitura de dados ...
escreval ("Digite o primeiro Numero:  ")
leia (x)
escreval ("Digite o segundo Numero : ")
leia (y)
escreval ("Digite o Terceiro Numero : ")
leia (z)


escreval ("Você Digitou : ", x , y, z )

Fimalgoritmo