Algoritmo "prova01_Exe01"
// Disciplina   : Algoritimo e Logica de Programacao
// Professor   : Getulio de Morais Pereira 
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/04/2022
Var
// variaveis 
raio, volume, pi : real 



Inicio
 

//inicio do programa
escreval ("-=-=-=-=-= Calculando o volume de uma esfera -=-=-=-=-=")
escreval ("-------------------------------------------------------")

//leitura e entrada de dados
escreval ("Digite o valor do Raio")
leia (raio)




Fimalgoritmo