Algoritmo "Numero Par ou impar"
// 
//
Var
// Secao de Declaraçes das variaveis

num : real


Inicio
   // Secao de Comandos, procedimento, funces, operadores, etc...
   num <- 0

   // leitura de dados
   escreval ("Digite o numero: ")
   leia  (num)

   //processamento de dados e saida.
   se( (num % 2) = 0 ) enta-o
      escreval ("Vocc digitou um numero par !")
   senao
      escreval ("Vocc ditigou um numero impar !")
   fimse
      
Fimalgoritmo