Algoritmo "Exercício 05"
// Disciplina   : Algorítimo e Lógica de Programação
// Professor   : Getúlio de Morais Pereira 
// Descrição   : Calculadora 
// Autor(a)    : Diogo Marinho da Silva
// Data atual  : 05/04/2022
Var
// Seção de Declarações das variáveis 
op : inteiro
val1, val2 : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("=-=-=-=-=- Calculadora Dinamica =-=-=-=-=-==")
escreval (" Digiti)


Fimalgoritmo
